-- Seed data for Vayutik App Marketplace

-- Insert categories
INSERT INTO public.categories (name, slug, description, icon) VALUES
  ('Productivity', 'productivity', 'Tools to boost your efficiency and workflow', 'Zap'),
  ('Design', 'design', 'Creative and design software', 'Palette'),
  ('Development', 'development', 'Developer tools and IDEs', 'Code'),
  ('Marketing', 'marketing', 'Marketing and growth tools', 'Megaphone'),
  ('Analytics', 'analytics', 'Data and analytics platforms', 'BarChart'),
  ('Communication', 'communication', 'Team collaboration and messaging', 'MessageSquare'),
  ('Finance', 'finance', 'Financial and accounting software', 'DollarSign'),
  ('AI Tools', 'ai-tools', 'Artificial intelligence powered applications', 'Sparkles')
ON CONFLICT (slug) DO NOTHING;

-- Insert sample apps
INSERT INTO public.apps (name, slug, tagline, description, category_id, icon_url, cover_url, website_url, pricing_type, price, developer_name, developer_url, featured, verified, total_installs, average_rating, review_count) VALUES
  (
    'Flowstate',
    'flowstate',
    'Deep work timer and focus companion',
    'Flowstate is a revolutionary focus app that combines pomodoro technique with ambient soundscapes. Enter deep work sessions, track your productivity patterns, and achieve flow state consistently. Features include customizable work intervals, break reminders, progress analytics, and integration with popular project management tools.',
    (SELECT id FROM public.categories WHERE slug = 'productivity'),
    'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=1200&h=600&fit=crop',
    'https://flowstate.app',
    'freemium',
    9.99,
    'Flowstate Labs',
    'https://flowstatelabs.com',
    true,
    true,
    45230,
    4.8,
    1250
  ),
  (
    'Pixelcraft Studio',
    'pixelcraft-studio',
    'AI-powered design tool for modern creators',
    'Pixelcraft Studio revolutionizes the design process with AI-assisted creation. From wireframes to high-fidelity mockups, create stunning visuals in minutes. Features smart layout suggestions, brand kit management, collaborative editing, and export to any format.',
    (SELECT id FROM public.categories WHERE slug = 'design'),
    'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&h=600&fit=crop',
    'https://pixelcraft.studio',
    'subscription',
    19.99,
    'Pixelcraft Inc',
    'https://pixelcraft.inc',
    true,
    true,
    32100,
    4.7,
    890
  ),
  (
    'CodeVault',
    'codevault',
    'Secure code snippet manager for developers',
    'CodeVault is the ultimate code snippet organizer. Store, search, and share code snippets across your team. Features syntax highlighting for 100+ languages, VS Code integration, GitHub sync, and AI-powered code suggestions.',
    (SELECT id FROM public.categories WHERE slug = 'development'),
    'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&h=600&fit=crop',
    'https://codevault.dev',
    'freemium',
    NULL,
    'CodeVault Team',
    'https://codevault.dev/team',
    true,
    true,
    67890,
    4.9,
    2340
  ),
  (
    'GrowthPilot',
    'growthpilot',
    'All-in-one marketing automation platform',
    'GrowthPilot automates your marketing workflows from email campaigns to social media scheduling. Connect with your audience at scale, analyze engagement metrics, and optimize campaigns with AI-driven insights.',
    (SELECT id FROM public.categories WHERE slug = 'marketing'),
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=600&fit=crop',
    'https://growthpilot.io',
    'subscription',
    49.99,
    'GrowthPilot HQ',
    'https://growthpilot.io',
    false,
    true,
    18450,
    4.5,
    567
  ),
  (
    'DataLens',
    'datalens',
    'Real-time analytics dashboard builder',
    'DataLens transforms complex data into beautiful, actionable dashboards. Connect multiple data sources, build custom visualizations, and share insights across your organization. Features include real-time updates, SQL queries, and embedded analytics.',
    (SELECT id FROM public.categories WHERE slug = 'analytics'),
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&h=600&fit=crop',
    'https://datalens.analytics',
    'paid',
    299.00,
    'DataLens Analytics',
    'https://datalens.analytics',
    true,
    true,
    12340,
    4.6,
    445
  ),
  (
    'TeamSync',
    'teamsync',
    'Async-first team communication hub',
    'TeamSync reinvents team communication for the remote era. Organized threads, async video messages, and smart notifications keep everyone aligned without the meeting fatigue. Integrates with Slack, Notion, and 50+ tools.',
    (SELECT id FROM public.categories WHERE slug = 'communication'),
    'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1200&h=600&fit=crop',
    'https://teamsync.co',
    'freemium',
    12.99,
    'TeamSync Labs',
    'https://teamsync.co',
    false,
    true,
    28900,
    4.4,
    789
  ),
  (
    'InvoiceFlow',
    'invoiceflow',
    'Modern invoicing and expense tracking',
    'InvoiceFlow streamlines your financial operations. Create professional invoices, track expenses, and get paid faster with integrated payment processing. Features include recurring invoices, expense categorization, and tax reports.',
    (SELECT id FROM public.categories WHERE slug = 'finance'),
    'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&h=600&fit=crop',
    'https://invoiceflow.finance',
    'subscription',
    14.99,
    'InvoiceFlow Inc',
    'https://invoiceflow.finance',
    false,
    true,
    34560,
    4.7,
    1120
  ),
  (
    'NeuralWrite',
    'neuralwrite',
    'AI writing assistant that thinks like you',
    'NeuralWrite learns your writing style and helps you create compelling content faster. From blog posts to marketing copy, get AI suggestions that sound authentically you. Features tone matching, plagiarism checking, and SEO optimization.',
    (SELECT id FROM public.categories WHERE slug = 'ai-tools'),
    'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1676299081847-824916de030a?w=1200&h=600&fit=crop',
    'https://neuralwrite.ai',
    'subscription',
    24.99,
    'NeuralWrite AI',
    'https://neuralwrite.ai',
    true,
    true,
    56780,
    4.8,
    1890
  ),
  (
    'SketchMind',
    'sketchmind',
    'Collaborative whiteboard for visual thinking',
    'SketchMind transforms brainstorming sessions into visual masterpieces. Real-time collaboration, infinite canvas, and smart shapes help teams ideate together. Perfect for design sprints, mind mapping, and remote workshops.',
    (SELECT id FROM public.categories WHERE slug = 'design'),
    'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1558655146-d09347e92766?w=1200&h=600&fit=crop',
    'https://sketchmind.design',
    'freemium',
    NULL,
    'SketchMind Studio',
    'https://sketchmind.design',
    false,
    true,
    23450,
    4.5,
    678
  ),
  (
    'APIForge',
    'apiforge',
    'Build and deploy APIs in minutes',
    'APIForge is the fastest way to create production-ready APIs. Visual API builder, automatic documentation, and one-click deployment. Supports REST and GraphQL with built-in authentication and rate limiting.',
    (SELECT id FROM public.categories WHERE slug = 'development'),
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=600&fit=crop',
    'https://apiforge.dev',
    'subscription',
    39.99,
    'APIForge Team',
    'https://apiforge.dev',
    true,
    true,
    19870,
    4.6,
    534
  ),
  (
    'ContentAI',
    'contentai',
    'AI-powered content creation and scheduling',
    'ContentAI revolutionizes content marketing. Generate blog posts, social media content, and marketing copy using advanced AI. Features include content calendar, multi-platform scheduling, and performance analytics.',
    (SELECT id FROM public.categories WHERE slug = 'marketing'),
    'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=1200&h=600&fit=crop',
    'https://contentai.marketing',
    'subscription',
    29.99,
    'ContentAI Labs',
    'https://contentai.marketing',
    false,
    true,
    41230,
    4.4,
    923
  ),
  (
    'VoiceFlow',
    'voiceflow',
    'Professional voice messaging for teams',
    'VoiceFlow brings the power of voice to team communication. Record async voice messages, transcribe meetings automatically, and search through audio archives. Perfect for remote teams and multilingual organizations.',
    (SELECT id FROM public.categories WHERE slug = 'communication'),
    'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=128&h=128&fit=crop',
    'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=1200&h=600&fit=crop',
    'https://voiceflow.team',
    'freemium',
    8.99,
    'VoiceFlow Inc',
    'https://voiceflow.team',
    false,
    true,
    15670,
    4.3,
    412
  )
ON CONFLICT (slug) DO NOTHING;
